export const ADD_CARD = "ADD_PLACE";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_PLACE";
export const SELECT_CARD = "SELECT_PLACE";
export const DESELECT_CARD = "DESELECT_PLACE";
export const SHOW_COMMENTS = "SHOW_COMMENTS";
export const HIDE_COMMENTS = "HIDE_COMMENTS";
export const TABLE_CURRENT_DATE = "TABLE_CURRENT_DATE";