// CardReducer
export const ADD_CARD = "ADD_PLACE";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_PLACE";
export const SELECT_CARD = "SELECT_PLACE";
export const DESELECT_CARD = "DESELECT_PLACE";
export const SHOW_COMMENTS = "SHOW_COMMENTS";
export const HIDE_COMMENTS = "HIDE_COMMENTS";
export const TABLE_CURRENT_DATE = "TABLE_CURRENT_DATE";
export const ADDING_CARD = "ADDING_CARD";

export const GET_CARDS_PENDING = "GET_CARDS_PENDING";
export const GET_CARDS_FULFILLED = "GET_CARDS_FULFILLED";
export const GET_CARDS_REJECTED = "GET_CARDS_REJECTED";

export const GO_TABLE_NEXT = "GO_TABLE_NEXT";
export const GO_TABLE_PREV = "GO_TABLE_PREV";

// ProfileReducer
export const GET_COURSES_FULFILLED = "GET_COURSES_FULFILLED";